const express = require('express');
const authRoutes = require('./auth.routes');
const termsRoutes = require('./terms.routes');
const classesRoutes = require('./classes.routes');
const subjectsRoutes = require('./subjects.routes');
const teachersRoutes = require('./teachers.routes');
const studentsRoutes = require('./students.routes');
const admissionsRoutes = require('./admissions.routes');
const attendanceRoutes = require('./attendance.routes');
const resultsRoutes = require('./results.routes');
const resultSheetsRoutes = require('./resultSheets.routes');
const feesRoutes = require('./fees.routes');
const dashboardRoutes = require('./dashboard.routes');
const reportsRoutes = require('./reports.routes');
const assignmentsRoutes = require('./assignments.routes');
const guardiansRoutes = require('./guardians.routes');
const feeStructuresRoutes = require('./feeStructures.routes');
const terminalReportsRoutes = require('./terminalReports.routes');
const announcementsRoutes = require('./announcements.routes');
const schoolSettingsRoutes = require('./schoolSettings.routes');
const auditLogsRoutes = require('./auditLogs.routes');
const notificationsRoutes = require('./notifications.routes');
const analyticsRoutes = require('./analytics.routes');
const assessmentSheetsRoutes = require('./assessmentSheets.routes');
const feedingFeesRoutes = require('./feedingFees.routes');
const verifyRoutes = require('./verify.routes');
const gradingSchemeRoutes = require('./gradingScheme.routes');
const personalAttributesRoutes = require('./personalAttributes.routes');
const aiRoutes = require('./ai.routes');
const earlyWarningRoutes = require('./earlyWarning.routes');
const superAdminRoutes = require('../superAdmin/routes');
const schoolRegistrationRoutes = require('./schoolRegistration.routes');
const examScheduleRoutes = require('./examSchedule.routes');
const intelligenceRoutes = require('./intelligence.routes');

const router = express.Router();

router.get('/health', (req, res) => {
  res.json({ success: true, data: { status: 'ok', timestamp: new Date().toISOString() } });
});

router.use('/auth', authRoutes);
router.use('/terms', termsRoutes);
router.use('/classes', classesRoutes);
router.use('/subjects', subjectsRoutes);
router.use('/teachers', teachersRoutes);
router.use('/students', studentsRoutes);
router.use('/admissions', admissionsRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/results', resultsRoutes);
router.use('/result-sheets', resultSheetsRoutes);
router.use('/fees', feesRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/reports', reportsRoutes);
router.use('/assignments', assignmentsRoutes);
router.use('/guardians', guardiansRoutes);
router.use('/fee-structures', feeStructuresRoutes);
router.use('/terminal-reports', terminalReportsRoutes);
router.use('/announcements', announcementsRoutes);
router.use('/school-settings', schoolSettingsRoutes);
router.use('/audit-logs', auditLogsRoutes);
router.use('/notifications', notificationsRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/assessment-sheets', assessmentSheetsRoutes);
router.use('/feeding-fees', feedingFeesRoutes);
router.use('/verify', verifyRoutes);
router.use('/grading-scheme', gradingSchemeRoutes);
router.use('/personal-attributes', personalAttributesRoutes);
router.use('/ai', aiRoutes);
router.use('/early-warning', earlyWarningRoutes);
router.use('/super-admin', superAdminRoutes);
router.use('/schools', schoolRegistrationRoutes);
router.use('/exam-schedules', examScheduleRoutes);
router.use('/intelligence', intelligenceRoutes);

module.exports = router;
